# Generated by Django 3.1.1 on 2021-05-19 13:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(max_length=2500)),
                ('content', wagtail.core.fields.StreamField([('intro', wagtail.core.blocks.StructBlock([('intro_title', wagtail.core.blocks.CharBlock(max_length=250)), ('description', wagtail.core.blocks.CharBlock(max_length=1000))])), ('title', wagtail.core.blocks.StructBlock([('page_title', wagtail.core.blocks.CharBlock(max_length=250)), ('description', wagtail.core.blocks.CharBlock(max_length=1000))])), ('category', wagtail.core.blocks.StructBlock([('category', wagtail.core.blocks.CharBlock(max_length=250)), ('description', wagtail.core.blocks.CharBlock(max_length=1000))])), ('question_range', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(max_length=1000)), ('q_type', wagtail.core.blocks.CharBlock(choices=['text', 'choice', 'range', 'email', 'tel', 'mutiple', 'infoText'], default='range', label='Question Type', max_length=250)), ('q_range', wagtail.core.blocks.IntegerBlock(default='5', label='Rating Range')), ('q_min', wagtail.core.blocks.CharBlock(default='1', label='Text for minimum end of scale', max_length=1000)), ('q_max', wagtail.core.blocks.CharBlock(default='5', label='Text for maximum end of scale', max_length=1000))])), ('question_multiple', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(max_length=500)), ('q_type', wagtail.core.blocks.CharBlock(choices=['text', 'choice', 'range', 'email', 'tel', 'mutiple', 'infoText'], default='multiple', label='Question Type', max_length=250)), ('q_2_3_choice_1', wagtail.core.blocks.CharBlock(label='Option 1', max_length=1000)), ('q_2_3_choice_2', wagtail.core.blocks.CharBlock(label='Option 2', max_length=1000)), ('q_2_3_choice_3', wagtail.core.blocks.CharBlock(label='Option 3', max_length=1000)), ('q_2_3_choice_4', wagtail.core.blocks.CharBlock(label='Option 4', max_length=1000)), ('q_2_3_choice_5', wagtail.core.blocks.CharBlock(label='Option 5', max_length=1000))])), ('record', wagtail.core.blocks.StructBlock([('record', wagtail.core.blocks.CharBlock(max_length=250))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
