# Generated by Django 3.1.1 on 2021-05-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20210525_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intakepage',
            name='intro',
        ),
    ]
