# Generated by Django 3.1.1 on 2021-04-05 18:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(max_length=150)),
                ('year_of_incorp', models.IntegerField()),
                ('age', models.CharField(max_length=3)),
                ('marital_status', models.CharField(max_length=7)),
                ('number_of_children', models.IntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
