# Generated by Django 3.1.1 on 2021-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_userrecord_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='age',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='marital_status',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='number_of_children',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='phone',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='year_of_incorp',
            field=models.CharField(max_length=150),
        ),
    ]
